### ISSUE TITLE
Example fails compilation "expected primary-expression before 'pulse'"

### ISSUE THREAD

**Issue by Arfski** [dvarrel/TM1638#1]
In the example, when run on an Arduino UNU R4, line 30 fails to compile unless "pulse" is in parentheses:

`tm.displaySetBrightness(pulse_t(pulse));`

**Comment by dvarrel** [comment]
better change line 16:
`pulse_t pulse = PULSE1_16;`

**Comment by dvarrel** [comment]
version 1.0.1

**Comment by Arfski** [comment]
A good point, rather than being populated in the next line.

Thank you for your library.
